name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install -D
    - name: yarn build
      run: |
        export REACT_APP_SHA_LONG="$(git rev-parse HEAD)" REACT_APP_SHA="$(git log -1 --pretty=tformat:%h HEAD)"
        yarn build
    - name: Extra patches
      run: |
        python -c 'import sys, os, json; json.dump(sorted(os.listdir("public/examples")), sys.stdout, sort_keys=True)' > build/examples/index.json
    - name: Deploy to GitHub Pages
      run: |
        CINFO="$(git log -1 --pretty="%an: [%h] %s")"
        git clone --depth=1 --branch=gh-pages --single-branch --no-checkout \
          "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" gittemp
        mv gittemp/.git build/.git && rmdir gittemp/
        pushd build/ &>/dev/null
        echo -n beep.ibugone.com > CNAME
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Auto deploy from GitHub Actions build ${GITHUB_RUN_NUMBER}" \
          -m "$CINFO"
        git push
        popd &>/dev/null
